# Generated by Django 4.2.6 on 2023-10-05 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brief_description', models.TextField(null=True)),
                ('detailed_description', models.TextField(null=True)),
                ('recommendation', models.TextField(null=True)),
                ('precautions', models.TextField(null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.company')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.destination')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='YachtType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.IntegerField(null=True)),
                ('sailing_boat', models.BooleanField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='sailor',
            name='image',
            field=models.ImageField(upload_to='sailor_images/'),
        ),
        migrations.CreateModel(
            name='Yacht',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='yacht_images/')),
                ('name', models.TextField(null=True)),
                ('year_built', models.IntegerField(null=True)),
                ('max_people', models.IntegerField(null=True)),
                ('price_per_night', models.FloatField(null=True)),
                ('no_cabins', models.IntegerField(null=True)),
                ('length_in_feet', models.FloatField(null=True)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.experience')),
                ('yacht_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.yachttype')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(null=True)),
                ('comment', models.TextField(null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.booking')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='experience_imgs/')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_imgs', to='main.experience')),
            ],
        ),
        migrations.AddField(
            model_name='destination',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.region'),
        ),
        migrations.AddField(
            model_name='booking',
            name='experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.experience'),
        ),
        migrations.AddField(
            model_name='booking',
            name='sailor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sailor'),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.bookingstatus'),
        ),
        migrations.AddField(
            model_name='booking',
            name='yacht',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.yacht'),
        ),
    ]
