# Generated by Django 4.2.6 on 2023-10-05 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_availability_booking_bookingstatus_destination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yacht',
            name='image',
            field=models.ImageField(upload_to='yacht_imgs/'),
        ),
    ]
