# Generated by Django 4.2.6 on 2023-10-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_yacht_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rating',
            new_name='Review',
        ),
        migrations.AddField(
            model_name='experience',
            name='name',
            field=models.CharField(default='Unforgettable adventure', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experience',
            name='brief_description',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='yacht',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='yacht_imgs/'),
        ),
    ]
