# Generated by Django 4.2.6 on 2023-10-13 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_experience_company_remove_yacht_experience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='experience',
        ),
        migrations.AddField(
            model_name='yacht',
            name='destination',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='main.destination'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
