# Generated by Django 4.2.6 on 2023-10-13 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_booking_experience_yacht_destination_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yacht',
            name='name',
        ),
        migrations.RemoveField(
            model_name='yacht',
            name='year_built',
        ),
    ]
