# Generated by Django 4.2.6 on 2023-10-18 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_yacht_name_remove_yacht_year_built'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='yacht',
        ),
        migrations.AddField(
            model_name='availability',
            name='yacht',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.yacht'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='availability',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.availability'),
            preserve_default=False,
        ),
    ]
