# Generated by Django 4.2.6 on 2023-10-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_booking_end_date_remove_booking_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yacht',
            name='name',
            field=models.CharField(default='El Malomi', max_length=30),
            preserve_default=False,
        ),
    ]
