# Generated by Django 4.2.6 on 2023-10-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_yacht_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sailor',
            name='image',
            field=models.ImageField(null=True, upload_to='sailor_images/'),
        ),
    ]
