# Generated by Django 4.2.6 on 2023-11-05 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_sailor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yacht',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='yacht_imgs/', verbose_name='image'),
        ),
    ]
