# Generated by Django 4.2.6 on 2023-11-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sailor',
            name='first_name',
            field=models.CharField(default='Martina', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sailor',
            name='last_name',
            field=models.CharField(default='Peres', max_length=20),
            preserve_default=False,
        ),
    ]
