# Generated by Django 4.2.6 on 2023-11-16 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_booking_confirmation_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='yacht',
            name='year_built',
            field=models.IntegerField(null=True),
        ),
    ]
