# Generated by Django 4.2.6 on 2023-12-02 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_passwordresetcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresetcode',
            name='created_at',
        ),
    ]
