# Generated by Django 4.2.6 on 2023-12-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_yacht_crewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yacht',
            name='crewed',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
