# Generated by Django 4.2.6 on 2023-12-05 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_yacht_crewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.destination'),
        ),
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='yacht',
            name='length_in_feet',
            field=models.FloatField(default=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='yacht',
            name='max_people',
            field=models.IntegerField(default=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='yacht',
            name='no_cabins',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='yacht',
            name='price_per_night',
            field=models.FloatField(default=350),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='yacht',
            name='year_built',
            field=models.IntegerField(default=1999),
            preserve_default=False,
        ),
    ]
